const listenNotesPodcasts = [
	{
		id: 'bf09da1c384f4910b5cd88b24d0afe47',
		rss: 'http://wherethemoneyis.libsyn.com/rss',
		type: 'episodic',
		email: 'industryfocus@fool.com',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/industry-focus-the-motley-fool-FgnhDWrQi4v-_HkAQ1m8DZy.1400x1400.jpg',
		title: 'Industry Anti-Focus - NO DUPLICATES',
		country: 'United States',
		website:
			'https://www.fool.com/podcasts/industry-focus?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 717428711,
		publisher: 'The Motley Fool',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/industry-focus-the-motley-fool-4vbTFDzLaik-_HkAQ1m8DZy.300x300.jpg',
		is_claimed: false,
		description:
			'Healthcare, technology, energy, consumer goods, and more. Every day, Motley Fool analysts break down a specific industry and the stocks making headlines. Questions? Comments? Email us at IndustryFocus@fool.com.',
		looking_for: '{...}',
		listen_score: 57,
		total_episodes: 1792,
		listennotes_url: 'https://www.listennotes.com/c/bf09da1c384f4910b5cd88b24d0afe47/',
		explicit_content: false,
		latest_pub_date_ms: 1608332486000,
		earliest_pub_date_ms: 1381335601701,
		listen_score_global_rank: '0.5%'
	},
	{
		id: 'dcc3f21204234e2fabf70d2d0fd0dd94',
		rss: 'https://einvestingforbeginners.com/feed/podcast/',
		type: 'episodic',
		email: 'sather_andrew@yahoo.com',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/the-investing-for-beginners-podcast-your-NjZ1SKFR0e4-1gOAxHUQYGK.1400x1400.jpg',
		title: 'The Investing for Beginners Podcast - Your Path to Financial Freedom',
		country: 'United States',
		website:
			'https://einvestingforbeginners.com?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 1210741497,
		publisher: 'Andrew Sather and Dave Ahern',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/the-investing-for-beginners-podcast-your-_A28ErMWdgK-1gOAxHUQYGK.300x300.jpg',
		is_claimed: false,
		description: 'How to Start Investing in the Stock Market for Beginners',
		looking_for: '{...}',
		listen_score: 57,
		total_episodes: 181,
		listennotes_url: 'https://www.listennotes.com/c/dcc3f21204234e2fabf70d2d0fd0dd94/',
		explicit_content: false,
		latest_pub_date_ms: 1608181260000,
		earliest_pub_date_ms: 1488366016172,
		listen_score_global_rank: '0.5%'
	},
	{
		id: 'c96d9f1b8f804a78851339fdb6f238d1',
		rss: 'https://feeds.redcircle.com/34df7015-ce8e-4451-bfa2-dd4ffe91e8b7',
		type: 'episodic',
		email: 'michael@earnyourleisure.com',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/market-mondays-eyl-network-bsCnFxK2Ht1-9pcQxoVlH6W.1400x1400.jpg',
		title: 'Market Mondays',
		country: 'United States',
		website:
			'https://redcircle.com/shows/marketmondays?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 1528535502,
		publisher: 'EYL Network',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/market-mondays-eyl-network-y1ESAqQC2dB-9pcQxoVlH6W.300x300.jpg',
		is_claimed: false,
		description:
			'<p>On Market Mondays, Earn Your Leisure and Stock market expert Ian Dunlap discuss strategies to make money in the stock market under any circumstance. During Market Mondays, we also answered a variety of investment questions from live callers. </p><p><br></p><p>Market Mondays is a new, exciting look into the world of investing and money management. </p>',
		looking_for: '{...}',
		listen_score: 57,
		total_episodes: 18,
		listennotes_url: 'https://www.listennotes.com/c/c96d9f1b8f804a78851339fdb6f238d1/',
		explicit_content: false,
		latest_pub_date_ms: 1608005104000,
		earliest_pub_date_ms: 1597931002014,
		listen_score_global_rank: '0.5%'
	},
	{
		id: 'fdcd719a5da64fe28bb6146a7fe1bf75',
		rss: 'http://feeds.feedburner.com/ReimagineWithEricSchmidt',
		type: 'episodic',
		email: 'info@compassmedianetworks.com',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/reimagine-with-eric-schmidt-schmidt-futures-fQGrNpqCMu--6W8BunTXPv-.1400x1400.jpg',
		title: 'Reimagine with Eric Schmidt',
		country: 'United States',
		website:
			'http://www.compassmedianetworks.com?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 1527837681,
		publisher: 'Schmidt Futures',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/reimagine-with-eric-schmidt-schmidt-futures-znuUDIFRCpG-6W8BunTXPv-.300x300.jpg',
		is_claimed: false,
		description:
			"COVID-19 is changing the way we live. We face the urgent challenges of combating the virus and getting people back to work. Once this crisis phase has passed - and under the shadow of its possible return - we must rebuild our economies, reintegrate all aspects of society, and reshape policy and practice around the world to be more resilient against global threats. <br><br> In Reimagine, former Google CEO and co-founder of Schmidt Futures Eric Schmidt will engage in conversations with the world's leaders in government, business, science, and technology to reimagine the future of society after COVID-19. Eric will draw upon his expertise as a global business leader, scientist, and philanthropist to explore how we can mobilize people and technology to solve our current challenges at scale and to build a brighter future after this global crisis. Each conversation will probe a local, national, or global facet of COVID-19 and some will feature a call to action for listeners or a prize competition for the best ideas related to the insights of the episode.",
		looking_for: '{...}',
		listen_score: 41,
		total_episodes: 14,
		listennotes_url: 'https://www.listennotes.com/c/fdcd719a5da64fe28bb6146a7fe1bf75/',
		explicit_content: false,
		latest_pub_date_ms: 1604952000000,
		earliest_pub_date_ms: 1597431600012,
		listen_score_global_rank: '2%'
	},
	{
		id: '54fdeb861d3b4797b6a23df24532d91f',
		rss: 'https://feeds.acast.com/public/shows/5f345a40da976b1d809f5714',
		type: 'episodic',
		email: 'info+5f345a40da976b1d809f5714@mg.pippa.io',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/business-on-the-bright-side-mwNCWT4K5Gn-soYlPGNm9kt.1400x1400.jpg',
		title: 'Business on the Bright Side',
		country: 'United States',
		website: 'https://jessekstrom.com/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 1527486300,
		publisher: 'Jess Ekstrom',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/business-on-the-bright-side-LreWS59yIXu-soYlPGNm9kt.300x300.jpg',
		is_claimed: false,
		description:
			"<p>Do you feel like you were made for more, but you don’t know where to begin? Do you have a story you want to tell, but you’re not sure how to tell it? Have you ever dreamed of speaking on stages, writing books and selling products that make both an impact and an income?&nbsp;</p><br><p>Well, you’ve come to the right place.</p><br><p>Named The Ultimate Game Changer by Women’s Health Magazine and Top Motivation Speaker by Forbes, Jess Ekstrom’s goal is to help women make a living and make a difference at the same time. As the bestselling author of Chasing the Bright Side, founder of Headbands of Hope and Bright Pages, Jess teaches from real life experiences (the good,&nbsp;the bad and the funny) in order to give you tangible tips and takeaways to help you craft your story that serves, so you can sell.&nbsp;</p><br><p>Jess believes life doesn’t have to be a tug-of-war between passion and profit...and she’s here to help you do both. This podcast is for people that DO, so episodes are short because we know you have places to be and we’re not going to waste your time.&nbsp;</p><br><p>Welcome to Business on the Bright Side with Jess Ekstrom.&nbsp;Let’s get started!</p><br /><hr><p style='color:grey; font-size:0.75em;'> See <a style='color:grey;' target='_blank' rel='noopener noreferrer' href='https://acast.com/privacy'>acast.com/privacy</a> for privacy and opt-out information.</p>",
		looking_for: '{...}',
		listen_score: 47,
		total_episodes: 20,
		listennotes_url: 'https://www.listennotes.com/c/54fdeb861d3b4797b6a23df24532d91f/',
		explicit_content: false,
		latest_pub_date_ms: 1608485416000,
		earliest_pub_date_ms: 1597266770013,
		listen_score_global_rank: '1%'
	},
	{
		id: 'f1fe96aad1d2403fa3b29b1b21ee8962',
		rss: 'http://popcornfinance.libsyn.com/rss',
		type: 'episodic',
		email: 'Questions@popcornfinance.com',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/popcorn-finance-chris-browning-fS0eWCPGsBt-N4fabLywrvV.1400x1400.jpg',
		title: 'Popcorn Finance',
		country: 'United States',
		website: 'http://popcornfinance.com?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 1254075020,
		publisher: 'Chris Browning',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/popcorn-finance-chris-browning-1w69oz3MDan-N4fabLywrvV.300x300.jpg',
		is_claimed: false,
		description:
			'An award winning short form podcast discussing finance in about the time it takes to make a bag of popcorn',
		looking_for: '{...}',
		listen_score: 47,
		total_episodes: 261,
		listennotes_url: 'https://www.listennotes.com/c/f1fe96aad1d2403fa3b29b1b21ee8962/',
		explicit_content: false,
		latest_pub_date_ms: 1608548400000,
		earliest_pub_date_ms: 1498676400244,
		listen_score_global_rank: '1%'
	},
	{
		id: 'ea5f7a003ac84fa98e4ea483e9fb62f2',
		rss: 'https://chachingpodcast.com/episodes-archive?format=rss',
		type: 'episodic',
		email: 'devilsfanatic30@hotmail.com',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/cha-ching-an-ecommerce-podcast-kevin-wild-t3rLISHeO-M-at3BZvKe8F6.1400x1400.jpg',
		title: 'Cha-Ching! - An eCommerce Podcast',
		country: 'United States',
		website:
			'https://chachingpodcast.com/episodes-archive/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 1323201793,
		publisher: 'Kevin Wild',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/cha-ching-an-ecommerce-podcast-kevin-wild-zqGINvXsmhM-at3BZvKe8F6.300x300.jpg',
		is_claimed: true,
		description:
			"Cha-Ching! is an eCommerce podcast where host, Kevin Wild, interviews merchants, app developers, and thought leaders on their experiences and successes with eCommerce. Every week, we will bring you an engaging discussion with someone deeply involved in the world of eCommerce. Whether it's dissecting a successful storeowner on how they managed to scale, or debating with a thought leader on where they see eCommerce going in the future, Cha-Ching! is the podcast for anyone and everyone involved with selling online.",
		looking_for: '{...}',
		listen_score: 31,
		total_episodes: 18,
		listennotes_url: 'https://www.listennotes.com/c/ea5f7a003ac84fa98e4ea483e9fb62f2/',
		explicit_content: false,
		latest_pub_date_ms: 1559235024000,
		earliest_pub_date_ms: 1512144112017,
		listen_score_global_rank: '5%'
	},
	{
		id: '37f7e9595b9d4350b281c8028c07d4f5',
		rss: 'https://feeds.simplecast.com/_Mc9bpsL',
		type: 'episodic',
		email: 'braveen.kumar@shopify.com',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/shopify-masters-the-ecommerce-business-and-43xl8gRMm0q-nRiTmsu0Bdy.1400x1400.jpg',
		title: 'Shopify Masters | The ecommerce business and marketing podcast for ambitious entrepreneurs',
		country: 'United States',
		website:
			'https://www.shopify.com/podcasts/shopify-masters?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 900763980,
		publisher: 'Shopify',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/shopify-masters-the-ecommerce-business-and-fRM5I6_cG-o-nRiTmsu0Bdy.300x300.jpg',
		is_claimed: false,
		description:
			'Shopify Masters is an official Shopify podcast where successful entrepreneurs and experts share their experience and inspirational stories. Each week, our host Felix Thea invites successful entrepreneurs to share their experience and practical advice for growing an online business on Shopify. Guests on the show come from a wide range of backgrounds and share insight into topics such as creating viral Facebook ads, outsourcing parts of your business, creating licensed products, running a newsworthy pop-up shop, optimizing your social media marketing, content marketing for SEO, and tons more. These are seasoned entrepreneurs that come from diverse backgrounds who are willing to pull back the curtain and share their best practical advice. Subscribe to the show and leave us a review to let us know what you think!',
		looking_for: '{...}',
		listen_score: 55,
		total_episodes: 304,
		listennotes_url: 'https://www.listennotes.com/c/37f7e9595b9d4350b281c8028c07d4f5/',
		explicit_content: false,
		latest_pub_date_ms: 1608006600000,
		earliest_pub_date_ms: 1455609600291,
		listen_score_global_rank: '0.5%'
	},
	{
		id: '8d62d3880db2425b890b986e58aca393',
		rss: 'http://feeds.soundcloud.com/users/soundcloud:users:55246524/sounds.rss',
		type: 'episodic',
		email: 'kmurdock@practicalecommerce.com',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/ecommerce-conversations-by-practical-i0ldgfQ4A1m.600x600.jpg',
		title: 'Ecommerce Conversations by Practical Ecommerce',
		country: 'United States',
		website:
			'http://www.practicalecommerce.com?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 874457373,
		publisher: 'Practical Ecommerce',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/ecommerce-conversations-by-practical-i0ldgfQ4A1m.300x300.jpg',
		is_claimed: false,
		description:
			'Listen in as host Eric Bandholz, founder of Beardbrand, interviews interesting entrepreneurs in the ecommerce space.',
		looking_for: '{...}',
		listen_score: 25,
		total_episodes: 315,
		listennotes_url: 'https://www.listennotes.com/c/8d62d3880db2425b890b986e58aca393/',
		explicit_content: false,
		latest_pub_date_ms: 1608304973000,
		earliest_pub_date_ms: 1200009600285,
		listen_score_global_rank: '10%'
	},
	{
		id: '9fbc8734149b4d508e45cacc4da35a89',
		rss: 'http://cashcowpro.libsyn.com/rss',
		type: 'episodic',
		email: 'hello@cashcowpro.com',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/amazon-fba-top-7-tips-cashcowpro-tips-for-y_iE3MIqhv4-oP2A-x8X9Qs.1400x1400.jpg',
		title: 'Amazon FBA Top 7 Tips',
		country: 'United States',
		website:
			'http://cashcowpro.libsyn.com/podcast?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 1106400592,
		publisher:
			'CashCowPro Tips for Amazon FBA Sellers Private Label Podcast, Scott Tomson and Mike Voelker share the most amazing seller tips, learn insider secrets for fulfilment by amazon!',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/amazon-fba-top-7-tips-cashcowpro-tips-for-recJg2YNEOy-oP2A-x8X9Qs.300x300.jpg',
		is_claimed: false,
		description:
			'Want to make more profit selling on Amazon FBA? Each episode covers the Top 7 tips in 5 minutes or less for actionable tips to win on Amazon. Our goal is to help you create a passive Amazon business that gives you cash flow while you enjoy doing what you love with your free time. The show covers Amazon FBA, Sourcing Products, Finding Suppliers, Amazon and Facebook PPC, Private Labelling, Promotions, Keywords, Product Selection, Increasing Sales, List building, being an Amazon Seller and much more.',
		looking_for: '{...}',
		listen_score: null,
		total_episodes: 209,
		listennotes_url: 'https://www.listennotes.com/c/9fbc8734149b4d508e45cacc4da35a89/',
		explicit_content: false,
		latest_pub_date_ms: 1486520086000,
		earliest_pub_date_ms: 1461234462208,
		listen_score_global_rank: null
	},
	{
		id: '2a38dcfb6cc946e59ce7661f58e6c300',
		rss: 'http://ecommercefuel.libsyn.com/rss',
		type: 'episodic',
		email: 'andrew@ecommercefuel.com',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/ecommerce-fuel-andrew-youderian-e-commerce-SLnEt5Jhp7u-yzfDrE1tSgd.1400x1400.jpg',
		title: 'eCommerce Fuel',
		country: 'United States',
		website: 'http://www.ecommercefuel.com?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 679570743,
		publisher: 'Andrew Youderian | e-Commerce Entrepreneur',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/ecommerce-fuel-andrew-youderian-e-commerce-PkvEoFM64Yc-yzfDrE1tSgd.300x300.jpg',
		is_claimed: false,
		description:
			"Looking for detailed information from top experts on researching, launching and growing your online eCommerce business? Look no further. Join your host Andrew Youderian, an experienced eCommerce entrepreneur, each week as he pulls aside some of the industry's top experts to give you down to earth, actionable advice served up with a side of comic relief. Learn from the masters how to turn your 'make money online' attempt into a profitable, growing online store. Get show notes, in-depth eCommerce Fuel posts and your free copy of Andrew's highly reviewed 55-page eCommerce guide at eCommercefuel.com.",
		looking_for: '{...}',
		listen_score: 52,
		total_episodes: 362,
		listennotes_url: 'https://www.listennotes.com/c/2a38dcfb6cc946e59ce7661f58e6c300/',
		explicit_content: false,
		latest_pub_date_ms: 1608289200000,
		earliest_pub_date_ms: 1374829923345,
		listen_score_global_rank: '0.5%'
	},
	{
		id: '758358627ea143f5a65b55df335962cc',
		rss: 'https://thefulltimefbashow.libsyn.com/rss',
		type: 'episodic',
		email: 'stephen@fulltimefba.com',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/the-full-time-fba-show-amazon-reseller-Mdb68uozRlP-MTaoW5wvU8n.1400x1400.jpg',
		title: 'The Full-Time FBA Show - Amazon Reseller Strategies & Stories',
		country: 'United States',
		website: 'http://www.fulltimefba.com?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 1467427607,
		publisher: 'Stephen & Rebecca Smotherman',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/the-full-time-fba-show-amazon-reseller-VpDbGEa_0Uv-MTaoW5wvU8n.300x300.jpg',
		is_claimed: false,
		description:
			"Sometimes selling on Amazon can be frustrating, but we're here to help. Hosted by Full-Time FBA's Stephen and Rebecca Smotherman, The Full-Time FBA Show is a podcast focused on helping you grow your Amazon FBA business to a point where you can make a full-time income with only part-time hours. We'll talk about the best Amazon FBA strategies and hear inspirational stories from those who have succeeded in making a full-time income with Amazon. The podcast features fresh content, proven strategies, and motivational interviews that are sure to help you take the next steps in growing your Amazon business.",
		looking_for: '{...}',
		listen_score: null,
		total_episodes: 62,
		listennotes_url: 'https://www.listennotes.com/c/758358627ea143f5a65b55df335962cc/',
		explicit_content: false,
		latest_pub_date_ms: 1608539400000,
		earliest_pub_date_ms: 1559930406052,
		listen_score_global_rank: null
	},
	{
		id: 'fc131f1086ee4eadb3fd9ea968fcf307',
		rss: 'https://theintrovertentrepreneur.podbean.com/feed.xml',
		type: 'episodic',
		email: 'beth@theintrovertentrepreneur.com',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/the-introvert-entrepreneur-beth-buelow-the-qr6CYFNA02W.1400x1400.jpg',
		title: 'The Introvert Entrepreneur',
		country: 'United States',
		website:
			'http://www.theintrovertentrepreneur.com/category/podcast?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 387593948,
		publisher: 'Beth Buelow, The Introvert Entrepreneur',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/the-introvert-entrepreneur-beth-buelow-the-qr6CYFNA02W.300x300.jpg',
		is_claimed: false,
		description: 'Success is an Inside Job! Info, Interviews & Inspiration for Introverts',
		looking_for: '{...}',
		listen_score: 44,
		total_episodes: 118,
		listennotes_url: 'https://www.listennotes.com/c/fc131f1086ee4eadb3fd9ea968fcf307/',
		explicit_content: false,
		latest_pub_date_ms: 1546285244000,
		earliest_pub_date_ms: 1402077875000,
		listen_score_global_rank: '1.5%'
	},
	{
		id: '74a86ed6d89a44a39c6fe7a594d5d21a',
		rss: 'https://feeds.megaphone.fm/supportissexy',
		type: 'episodic',
		email: 'elayne@elaynefluker.com',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/support-is-sexy-podcast-with-elayne-fluker-koJ804nDe_s-p24IPURTui6.1400x1400.jpg',
		title: 'Support is Sexy Podcast with Elayne Fluker | Interviews with 500+ Successful Women Entrepreneurs!',
		country: 'United States',
		website: 'http://elaynefluker.com/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 1129580395,
		publisher: 'Elayne Fluker: Entrepreneur, Author, Speaker, Coach and Consultant',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/support-is-sexy-podcast-with-elayne-fluker-OX18VzMvti9-p24IPURTui6.300x300.jpg',
		is_claimed: false,
		description:
			'Elayne Fluker is author of the new book, Get Over ‘I Got It’: How to Stop Playing Superwoman, Get Support and Remember that Having It All Doesn’t Mean Doing It All Alone (HarperCollins Leadership). As host of the SUPPORT IS SEXY podcast, Elayne interviews more than 500 successful women entrepreneurs around the world, who share inspiring, true stories of the ups and the downs of their entrepreneurial journeys. Elayne Fluker is also founder of SiS.Academy, an online learning platform for women entrepreneurs. For more information about Elayne Fluker, please visit elaynefluker.com. Thank you for listening!',
		looking_for: '{...}',
		listen_score: 47,
		total_episodes: 764,
		listennotes_url: 'https://www.listennotes.com/c/74a86ed6d89a44a39c6fe7a594d5d21a/',
		explicit_content: false,
		latest_pub_date_ms: 1608026400000,
		earliest_pub_date_ms: 1467247560751,
		listen_score_global_rank: '1%'
	},
	{
		id: 'f763426f7241497f806017bcaed8df2d',
		rss: 'http://feeds.backtracks.fm/feeds/st/twist/feed.xml?1594222988',
		type: 'episodic',
		email: 'm.monaco@stockstotrade.com',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/twist-matthew-monaco-1bHQid5Yhau-cyJAYs0xjfU.1400x1400.jpg',
		title: 'TWIST',
		country: 'United States',
		website: 'https://steadytrade.com/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 1522711647,
		publisher: 'Matthew Monaco',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/twist-matthew-monaco-1G_KWoISYEh-cyJAYs0xjfU.300x300.jpg',
		is_claimed: false,
		description:
			'Every week different stocks are moving in the market... but how can you play them? TWIST lets you sit down with three, highly profitable traders to discuss the best plays of the week.',
		looking_for: '{...}',
		listen_score: 46,
		total_episodes: 32,
		listennotes_url: 'https://www.listennotes.com/c/f763426f7241497f806017bcaed8df2d/',
		explicit_content: false,
		latest_pub_date_ms: 1608228300000,
		earliest_pub_date_ms: 1587074280011,
		listen_score_global_rank: '1%'
	},
	{
		id: 'a7d4dbb3e8b94b67ab702bbb076c0e8d',
		rss: 'http://feeds.soundcloud.com/users/soundcloud:users:24345662/sounds.rss',
		type: 'episodic',
		email: 'brentleary@gmail.com',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/one-on-one-interviews-small-business-trends-2K4W0oUiBd1.1400x1400.jpg',
		title: 'One on One Interviews',
		country: 'United States',
		website: 'http://smallbiztrends.com?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 1023250761,
		publisher: 'Brent Leary and Small Business Trends',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/one-on-one-interviews-small-business-trends-2K4W0oUiBd1.300x300.jpg',
		is_claimed: true,
		description: 'Podcast by Brent Leary and Small Business Trends',
		looking_for: '{...}',
		listen_score: 25,
		total_episodes: 343,
		listennotes_url: 'https://www.listennotes.com/c/a7d4dbb3e8b94b67ab702bbb076c0e8d/',
		explicit_content: false,
		latest_pub_date_ms: 1608305643000,
		earliest_pub_date_ms: 1348124565322,
		listen_score_global_rank: '10%'
	},
	{
		id: '536ee2ed96224ea79dfd944c166df86e',
		rss: 'http://businessofstory.libsyn.com/rss',
		type: 'episodic',
		email: 'park@businessofstory.com',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/business-of-story-park-howell-trusted-brand-TCdMkOScYyh-ZTmcq3A0_h6.1024x1024.jpg',
		title: 'Business of Story',
		country: 'United States',
		website: 'http://businessofstory.com?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 1012379862,
		publisher: 'Park Howell, Brand Story Strategist',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/business-of-story-park-howell-trusted-brand-Y30BxGwFNzo-ZTmcq3A0_h6.300x300.jpg',
		is_claimed: false,
		description:
			'The Business of Story podcast, hosted by Park Howell, is one of the top brand storytelling podcasts and named among 40 Best Small Business Podcasts in 2017. It will help you reignite within you the one true superpower we all possess - storytelling. Each episode provides the best strategies and secrets from the best content creators, advertising creatives, authors, screenwriters, entrepreneurs, marketers, and brand raconteurs that show you how to make your story marketing stand out. You will learn how to connect with your customers, move them to action, and start creating epic growth for your organization and your people.',
		looking_for: '{...}',
		listen_score: 47,
		total_episodes: 288,
		listennotes_url: 'https://www.listennotes.com/c/536ee2ed96224ea79dfd944c166df86e/',
		explicit_content: false,
		latest_pub_date_ms: 1608534060000,
		earliest_pub_date_ms: 1434556800263,
		listen_score_global_rank: '1%'
	},
	{
		id: '4e4a505f28124218a67ddffeb3f85a12',
		rss: 'https://anchor.fm/s/2e9b7c8c/podcast/rss',
		type: 'episodic',
		email: null,
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/how-to-start-a-startup-5PAcXSkzIU1-dnhlLxwtrSJ.1400x1400.jpg',
		title: 'How to start a startup? ',
		country: 'United States',
		website: null,
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 1526466201,
		publisher: 'Startupersclub',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/how-to-start-a-startup-9P0wszfjW7T-dnhlLxwtrSJ.300x300.jpg',
		is_claimed: false,
		description: 'How to start a startup? ',
		looking_for: '{...}',
		listen_score: null,
		total_episodes: 3,
		listennotes_url: 'https://www.listennotes.com/c/4e4a505f28124218a67ddffeb3f85a12/',
		explicit_content: false,
		latest_pub_date_ms: 1597048776000,
		earliest_pub_date_ms: 1596620025002,
		listen_score_global_rank: null
	},
	{
		id: 'eff46d01cb0d4dd3ba6ef64a2b217adf',
		rss: 'https://feeds.simplecast.com/Yv_K3b7p',
		type: 'episodic',
		email: 'theentrepreneurcast@gmail.com',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/the-entrepreneur-cast-sam-mcroberts-jayson-UGNbY4JxPnv-Xbaf3mndKrl.1400x1400.jpg',
		title: 'The Entrepreneur Cast',
		country: 'United States',
		website:
			'https://theentrepreneurcast.com/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 1507686604,
		publisher: 'Jayson DeMers, Sam McRoberts',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/the-entrepreneur-cast-sam-mcroberts-jayson-zXChp8OInek-Xbaf3mndKrl.300x300.jpg',
		is_claimed: false,
		description:
			"Are you an entrepreneur? Do you wish you were? Serial entrepreneurs Jayson DeMers and Sam McRoberts will walk you through all the various aspects of entrepreneurship, from starting and running a business, to digital marketing, SEO, psychology, copywriting and so much more. The biggest struggle for most entrepreneurs is that they don't know what they don't know...and that's where Sam and Jayson come to the rescue. They'll fill in the knowledge gaps, and lead you through your entrepreneurial journey from end-to-end. Sam McRoberts is the CEO of VUDU Marketing, an SEO agency that specializes in audits, strategies and consulting. He is also the bestselling author of Screw the Zoo, a writer for Inc. and Entrepreneur, and a digital nomad who travels the world with his family non-stop. Jayson DeMers is the founder and CEO of Email Analytics, a SaaS tool for improving email productivity for sales teams, account managers and customer service reps. He is also the former founder and CEO of AudienceBloom (acquired), and a prolific writer whose work has been seen on Forbes, Inc., Entrepreneur, Business Insider, and dozens of other media outlets. The Entrepreneur Cast will air every Monday, and will be available on iTunes, Spotify, Overcast and other platforms. The format is fireside chat with co-hosts, though the occasional guest may join the show.",
		looking_for: '{...}',
		listen_score: 32,
		total_episodes: 52,
		listennotes_url: 'https://www.listennotes.com/c/eff46d01cb0d4dd3ba6ef64a2b217adf/',
		explicit_content: true,
		latest_pub_date_ms: 1604342365000,
		earliest_pub_date_ms: 1586714572007,
		listen_score_global_rank: '5%'
	},
	{
		id: '9a3df8b38afe478c8caf22a7d2c3c00a',
		rss: 'http://schoolofselfmastery.libsyn.com/rss',
		type: 'episodic',
		email: 'adrienne@adriennedorison.com',
		extra: '{...}',
		image:
			'https://cdn-images-1.listennotes.com/podcasts/the-school-of-self-mastery-business-money-nOapIdujsYr-FGn1IJuoms0.1400x1400.jpg',
		title: 'The School of Self-Mastery: Business, Money, Life',
		country: 'United States',
		website:
			'http://schoolofselfmastery.libsyn.com/podcast?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website',
		language: 'English',
		genre_ids: '[...]',
		itunes_id: 1022041617,
		publisher: 'Adrienne Dorison',
		thumbnail:
			'https://cdn-images-1.listennotes.com/podcasts/the-school-of-self-mastery-business-money-j1REgW953rh-FGn1IJuoms0.300x300.jpg',
		is_claimed: true,
		description:
			"The School of Self-Mastery podcast is dedicated to helping listeners reach their highest potential by talking all things business, money, and life. I talk to guests who have created a RICH life for themselves, not because they’re bathing in money, (although they may be doing that too) but because they’ve defined and created success on their own terms, through successful habits. Monday through Friday you'll hear from top business and money minds sharing their valuable insights and we dive deep into their own personal success habits. This is the place where you come to master the person most responsible for your success...you.",
		looking_for: '{...}',
		listen_score: 43,
		total_episodes: 256,
		listennotes_url: 'https://www.listennotes.com/c/9a3df8b38afe478c8caf22a7d2c3c00a/',
		explicit_content: false,
		latest_pub_date_ms: 1495432800000,
		earliest_pub_date_ms: 1437627600255,
		listen_score_global_rank: '1.5%'
	}
];

export default listenNotesPodcasts;
