export const dbCategoryList = [
	{ id: 1, name: '*' },
	{ id: 2, name: 'Arts' },
	{ id: 3, name: 'Business' },
	{ id: 4, name: 'Comedy' },
	{ id: 6, name: 'Education' },
	{ id: 8, name: 'Fiction' },
	{ id: 10, name: 'Government' },
	{ id: 11, name: 'Health & Fitness' },
	{ id: 12, name: 'History' },
	{ id: 13, name: 'Kids & Family' },
	{ id: 14, name: 'Leisure' },
	{ id: 15, name: 'Music' },
	{ id: 17, name: 'News' },
	{ id: 19, name: 'Religion & Spirituality' },
	{ id: 20, name: 'Science' },
	{ id: 22, name: 'Society & Culture' },
	{ id: 23, name: 'Sports' },
	{ id: 24, name: 'Technology' },
	{ id: 25, name: 'True Crime' },
	{ id: 26, name: 'video' }
];
